In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
b = [1,2,3,4]

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b

[1, 2, 3, 4]

In [6]:
print(a)

[1 2 3 4]


In [7]:
print(b)

[1, 2, 3, 4]


In [24]:
a = a + 1
print(a)

[ 9 10 11 12]


In [26]:
b = b + [1]
print(b)

[1, 2, 3, 4, 1]
